name       : python-pyzstd
version    : 0.15.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/p/pyzstd/pyzstd-0.15.6.tar.gz : 32a1b67d5340d8df381e718a788417455edd76bed7e8a4cbd259acdc30b5e17e
homepage   : https://github.com/animalize/pyzstd
license    : BSD-3-Clause
component  : programming.python
summary    : Python bindings to Zstandard (zstd) compression library, the API style is similar to Python's bz2/lzma/zlib modules.
description: |
    Pyzstd module provides classes and functions for compressing and decompressing data, using Facebook's Zstandard (or zstd as short name) algorithm.
builddeps  :
    - pkgconfig(python3)
    - python-build
    - python-installer
    - python-pytest      # check
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
